galaxy/accounts/urls.py
# (c) 2012-2016, Ansible by Red Hat
#
# This file is part of Ansible Galaxy
#
# Ansible Galaxy is free software: you can redistribute it and/or modify
# it under the terms of the Apache License as published by
# the Apache Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Ansible Galaxy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Apache License for more details.
#
# You should have received a copy of the Apache License
# along with Galaxy.  If not, see <http://www.apache.org/licenses/>.

from django.conf.urls import patterns, url
from . import views


urlpatters = patterns(
    '',
    url(r'^dashboard/$', views.dashboard, name='accounts_dashboard'),

)

galaxy/api/urls.py
# (c) 2012-2016, Ansible by Red Hat
#
# This file is part of Ansible Galaxy
#
# Ansible Galaxy is free software: you can redistribute it and/or modify
# it under the terms of the Apache License as published by
# the Apache Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Ansible Galaxy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Apache License for more details.
#
# You should have received a copy of the Apache License
# along with Galaxy.  If not, see <http://www.apache.org/licenses/>.

from django.conf.urls import include, patterns, url as original_url
from rest_framework import routers
from .views import (RoleSearchView,
                    FacetedView,
                    PlatformsSearchView,
                    TagsSearchView,
                    ApiV1SearchView,
                    ApiV1ReposView,
                    UserSearchView,
                    TokenView,
                    RemoveRole,
                    RefreshUserRepos)

router = routers.DefaultRouter()
router.register('v1/search/roles', RoleSearchView, base_name="search-roles")


def url(regex, view, kwargs=None, name=None, prefix=''):
    # Set default name from view name (if a string).
    if isinstance(view, basestring) and name is None:
        name = view
    return original_url(regex, view, kwargs, name, prefix)

user_urls = patterns(
    'galaxy.api.views',
    url(r'^$',                              'user_list'),
    url(r'^(?P<pk>[0-9]+)/$',               'user_detail'),
    url(r'^(?P<pk>[0-9]+)/repos/$',         'user_repositories_list'),
    url(r'^(?P<pk>[0-9]+)/subscriptions/$', 'user_subscription_list'),
    url(r'^(?P<pk>[0-9]+)/starred/$',       'user_starred_list'),
    url(r'^(?P<pk>[0-9]+)/secrets/$',       'user_notification_secret_list'),    
)

role_urls = patterns(
    'galaxy.api.views',
    url(r'^$',                         'role_list'),
    url(r'^(?P<pk>[0-9]+)/$',          'role_detail'),
    url(r'^(?P<pk>[0-9]+)/users/$',    'role_users_list'),
    url(r'^(?P<pk>[0-9]+)/dependencies/$', 'role_dependencies_list'),
    url(r'^(?P<pk>[0-9]+)/imports/$',  'role_import_task_list'),
    url(r'^(?P<pk>[0-9]+)/versions/$', 'role_versions_list'),
    url(r'^(?P<pk>[0-9]+)/notifications/$', 'role_notification_list')
)

platform_urls = patterns(
    'galaxy.api.views',
    url(r'^$',                         'platform_list'),
    url(r'^(?P<pk>[0-9]+)/$',          'platform_detail'),
)

category_urls = patterns(
    'galaxy.api.views',
    url(r'^$',                         'category_list'),
    url(r'^(?P<pk>[0-9]+)/$',          'category_detail'),
)

tag_urls = patterns(
    'galaxy.api.views',
    url(r'^$',                         'tag_list'),
    url(r'^(?P<pk>[0-9]+)/$',          'tag_detail'),
)

search_urls = patterns(
    'galaxy.api.views',
    url(r'^$',                           ApiV1SearchView.as_view(), name="search_view"),
    # url(r'facetedplatforms/$',           FacetedView.as_view(),
    #    kwargs={u'facet_key': u'platforms', u'model': u'Role'}, name="faceted_platforms_view"),
    #url(r'facetedtags/$',                FacetedView.as_view(),
    #    kwargs={u'facet_key': u'tags', u'model': u'Role'}, name="faceted_tags_view"),
    url(r'platforms/$',                  PlatformsSearchView.as_view(), name='platforms_search_view'),
    url(r'tags/$',                       TagsSearchView.as_view(), name='tags_search_view'),
    url(r'users/$',                      UserSearchView.as_view(), name='user_search_view'),
    url(r'top_contributors/$',           'top_contributors_list', name='top_contributors_list'),
)

import_task_urls = patterns(
    'galaxy.api.views',
    url(r'^$',                              'import_task_list'),
    url(r'latest/$',                        'import_task_latest_list'),
    url(r'^(?P<pk>[0-9]+)/$',               'import_task_detail'),
    url(r'^(?P<pk>[0-9]+)/notifications/$', 'import_task_notification_list'),
)

notification_secret_urls = patterns(
    'galaxy.api.views',
    url(r'^$',                         'notification_secret_list'),
    url(r'^(?P<pk>[0-9]+)/$',          'notification_secret_detail'),
)

notification_urls = patterns(
    'galaxy.api.views',
    url(r'^$',                         'notification_list'),
    url(r'^(?P<pk>[0-9]+)/$',          'notification_detail'),
    url(r'^(?P<pk>[0-9]+)/roles/$',    'notification_roles_list'),
    url(r'^(?P<pk>[0-9]+)/imports/$',  'notification_imports_list'),    
)

repo_urls = patterns(
    'galaxy.api.views',
    url(r'^$',                             ApiV1ReposView.as_view(), name="repos_view"),
    url(r'list/$',                         'repository_list'),
    url(r'list/(?P<pk>[0-9]+)/$',          'repository_detail'),
    url(r'refresh/$',                      RefreshUserRepos.as_view(), name='refresh_user_repos'),
    url(r'stargazers/$',                   'stargazer_list'),
    url(r'stargazers/(?P<pk>[0-9]+)/$',    'stargazer_detail'),
    url(r'subscriptions/$',                'subscription_list'),
    url(r'subscriptions/(?P<pk>[0-9]+)/$', 'subscription_detail'),
)

v1_urls = patterns(
    'galaxy.api.views',
    url(r'^$',                         'api_v1_root_view'),
    url(r'^me/$',                      'user_me_list'),
    url(r'^users/',                    include(user_urls)),
    url(r'^roles/',                    include(role_urls)),
    url(r'^role_types/',               'role_types'),
    url(r'^categories/',               include(category_urls)),
    url(r'^tags/',                     include(tag_urls)),
    url(r'^platforms/',                include(platform_urls)),
    url(r'^imports/',                  include(import_task_urls)),
    url(r'^tokens/',                   TokenView.as_view(), name='token'),
    url(r'^removerole/',               RemoveRole.as_view(), name='remove_role'),
    url(r'^notification_secrets/',     include(notification_secret_urls)),
    url(r'^notifications/',            include(notification_urls)),
    url(r'^repos/',                    include(repo_urls)),
    url(r'^search/',                   include(search_urls)),
)

urlpatterns = patterns(
    'galaxy.api.views',
    url(r'^$',                         'api_root_view'),
    url(r'^v1/',                       include(v1_urls)),
)

urlpatterns += router.urls

galaxy/main/urls.py
# (c) 2012-2016, Ansible by Red Hat
#
# This file is part of Ansible Galaxy
#
# Ansible Galaxy is free software: you can redistribute it and/or modify
# it under the terms of the Apache License as published by
# the Apache Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Ansible Galaxy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Apache License for more details.
#
# You should have received a copy of the Apache License
# along with Galaxy.  If not, see <http://www.apache.org/licenses/>.

from django.conf.urls import patterns, url
from galaxy.main.views import RoleListView, RoleDetailView, NamespaceListView
from django.conf import settings
from django.contrib.staticfiles import views

urlpatterns = patterns(
    'galaxy.main.views',
    # Non-secure URLs
    url(r'^$', 'home', name='home'),
    url(r'^explore$', 'explore', name='explore'),
    url(r'^intro$', 'intro', name='intro'),
    url(r'^accounts/landing[/]?$', 'accounts_landing', name='accounts-landing'),
    url(r'^list$', 'list_category', name='list-category'),
    url(r'^detail$', 'detail_category', name='detail-category'),
    url(r'^roleadd$', 'role_add_view', name='role-add-category'),
    url(r'^imports$', 'import_status_view', name='import-status'),
    
    # Logged in/secured URLs
    url(r'^accounts/connect/$', 'accounts_connect'),
    url(r'^accounts/connect/success/$', 'accounts_connect_success', name='accounts-connect-success'),
    url(r'^accounts/profile/$', 'accounts_profile', name='accounts-profile'),
    #url(r'^accounts/role/view/(?P<role>[\w\-\._:]+)$', 'accounts_role_view', name='accounts-role-view'),
    #url(r'^accounts/role/refresh/(?P<id>[\w\-\._:]+)$', 'accounts_role_refresh', name='accounts-role-refresh'),
    
    # Secure Action URLs
    #url(r'^accounts/role/save$', 'accounts_role_save', name='accounts-role-save'),
    #url(r'^accounts/role/delete/(?P<id>[0-9]+)$', 'accounts_role_delete', name='accounts-role-delete'),
    #url(r'^accounts/role/deactivate/(?P<id>[0-9]+)$', 'accounts_role_deactivate', name='accounts-role-deactivate'),
    #url(r'^accounts/role/reactivate/(?P<id>[0-9]+)$', 'accounts_role_reactivate', name='accounts-role-reactivate'),

    url(r'^authors/$', NamespaceListView.as_view(), name='namespace-list'),
    url(r'^([\w\-._+]+)/$', RoleListView.as_view(), name='role-list'),
    url(r'^([\w\-._+]+)/([\w\-._+]+)/$', RoleDetailView.as_view(), name='role-detail'),
)

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

galaxy/urls.py
# (c) 2012-2016, Ansible by Red Hat
#
# This file is part of Ansible Galaxy
#
# Ansible Galaxy is free software: you can redistribute it and/or modify
# it under the terms of the Apache License as published by
# the Apache Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Ansible Galaxy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Apache License for more details.
#
# You should have received a copy of the Apache License
# along with Galaxy.  If not, see <http://www.apache.org/licenses/>.

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
import autofixture

handler404 = 'galaxy.main.views.handle_404_view'
handler400 = 'galaxy.main.views.handle_400_view'
handler500 = 'galaxy.main.views.handle_500_view'

admin.autodiscover()
autofixture.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api/', include('galaxy.api.urls', namespace='api', app_name='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^avatar/', include('avatar.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    url(r'', include('galaxy.main.urls', namespace='main', app_name='main')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls))
    )

galaxy/accounts/forms.py
# (c) 2012-2016, Ansible by Red Hat
#
# This file is part of Ansible Galaxy
#
# Ansible Galaxy is free software: you can redistribute it and/or modify
# it under the terms of the Apache License as published by
# the Apache Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Ansible Galaxy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Apache License for more details.
#
# You should have received a copy of the Apache License
# along with Galaxy.  If not, see <http://www.apache.org/licenses/>.

from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.utils.translation import ugettext_lazy as _

from .models import CustomUser


class CustomUserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    username = forms.RegexField(
        label=_("Username"),
        max_length=30,
        regex=r'^[\w.@+-]+$',
        help_text=_("Required. 30 characters or fewer. Letters, digits and "
                    "@/./+/-/_ only."),
        error_messages={
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as above, for verification."))

    class Meta:
        # Point to our CustomUser here instead of default `User`
        model = CustomUser
        fields = ("username",)

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            # Refer to our CustomUser here instead of default `User`
            CustomUser._default_manager.get(username=username)
        except CustomUser.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        # Make sure we pass back in our CustomUserCreationForm and not the
        # default `UserCreationForm`
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class CustomUserChangeForm(forms.ModelForm):
    username = forms.RegexField(
        label=_("Username"),
        max_length=30,
        regex=r"^[\w.@+-]+$",
        help_text=_("Required. 30 characters or fewer. Letters, digits and "
                    "@/./+/-/_ only."),
        error_messages={
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    password = ReadOnlyPasswordHashField(
        label=_("Password"),
        help_text=_("Raw passwords are not stored, so there is no way to see "
                    "this user's password, but you can change the password "
                    "using <a href=\"password/\">this form</a>."))

    class Meta:
        # Point to our CustomUser here instead of default `User`
        model = CustomUser
        exclude = ()

    def __init__(self, *args, **kwargs):
        # Make sure we pass back in our CustomUserChangeForm and not the
        # default `UserChangeForm`
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

galaxy/main/forms.py
# (c) 2012-2016, Ansible by Red Hat
#
# This file is part of Ansible Galaxy
#
# Ansible Galaxy is free software: you can redistribute it and/or modify
# it under the terms of the Apache License as published by
# the Apache Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Ansible Galaxy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Apache License for more details.
#
# You should have received a copy of the Apache License
# along with Galaxy.  If not, see <http://www.apache.org/licenses/>.

galaxy/accounts/views.py
# (c) 2012-2016, Ansible by Red Hat
#
# This file is part of Ansible Galaxy
#
# Ansible Galaxy is free software: you can redistribute it and/or modify
# it under the terms of the Apache License as published by
# the Apache Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Ansible Galaxy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Apache License for more details.
#
# You should have received a copy of the Apache License
# along with Galaxy.  If not, see <http://www.apache.org/licenses/>.

# Create your views here.

galaxy/templates/base.html
{% extends 'master.html' %}

{% block content %}
<div class="main page-content">
{% block general_content %}{% endblock %}
</div>

{% if load_angular %}
<script>
    /*
     * Provide current user info
     */
    'use strict';
    (function(angular) {

        var mod = angular.module('currentUserService', ['ngResource']);

        mod.factory('currentUserService', ['$resource', _factory]);

        function _factory($resource) {
            var userData = {
                "id": ("{{ user.id }}" == "None") ? null : parseInt("{{ user.id }}"),
                "authenticated": ("{{ user.is_authenticated }}" == "True") ? true : false, 
                "staff": ("{{ user.is_staff }}" == "True") ? true : false, 
                "username": "{{ user.username }}", 
                "created": ("{{ user.date_joined }}" == "") ? null : "{{ user.date_joined }}", 
                "modified": ("{{ user.last_login }}" == "") ? null : "{{ user.last_login }}", 
                "active": ("{{ user.is_active }}" == "True") ? true : false,
                "connected_to_github": ("{{ connected_to_github }}" == "True") ? true : false,
                "cache_refreshed": ("{{ user.cache_refreshed }}" == "True") ? true : false,
                "auth_orgs_url": "{{ auth_orgs_url }}",
                "subscriptions": [
                    {% for subscription in user.get_subscriptions %}
                        {
                           id: {{ subscription.id }},
                           github_user: "{{ subscription.github_user }}",
                           github_repo: "{{ subscription.github_repo }}"
                        }
                        {% if not forloop.last %},{%  endif %}
                    {% endfor %}
                ],
                "starred": [
                    {% for star in user.get_starred %}
                        {
                           id: {{ star.id }},
                           github_user: "{{ star.github_user }}",
                           github_repo: "{{ star.github_repo }}"
                        }
                        {% if not forloop.last %},{%  endif %}
                    {% endfor %}
                ],
                "update": function() {
                    // refresh anything about the user that may change
                    return $resource('/api/v1/users/' + userData.id + '/').get().$promise.then(function(response) {
                        userData.cache_refreshed = response.cache_refreshed;
                        userData.subscriptions = response.summary_fields.subscriptions;
                        userData.starred = response.summary_fields.starred;
                        return userData;
                    });
                }
            };

            return userData;
        }
    })(angular);
</script>
{% endif %}


{% endblock %}

galaxy/templates/custom400.html
{% extends 'base.html' %}

{% block general_content %}

<div id="galaxy-page-title">
    <div class="container-fluid">
        <div class="page-title">What?!</div>
    </div>
</div>

<div id="galaxy-page-not-found">
    <div class="title"><span class="error-number">400</span> Page Not found</div>
    <p class="text-message">
        The requested page could not be found.
    </p>
</div>

{% endblock %}

galaxy/templates/custom404.html
{% extends 'base.html' %}

{% block general_content %}

<div id="galaxy-page-title">
    <div class="container-fluid">
        <div class="page-title">What?!</div>
    </div>
</div>

<div id="galaxy-page-not-found">
    <div class="title"><span class="error-number">404</span> Page Not found</div>
    <p class="text-message">
        The requested page could not be found.
    </p>
</div>

{% endblock %}

galaxy/templates/explore.html
{% extends 'base.html' %}

{% load galaxyhelpers %}

{% block general_content %}
 <div ng-view></div>
{% endblock %}

galaxy/templates/footer.html
{% block extra_body %}{% endblock %}

<div id="footer-content">
    {% if not url_items_length or url_items_length > 1 %}
    <div id="galaxy-footer-blue-line" class="container-fluid"></div>
    {% endif %}

    <div id="galaxy-copyright"{% if url_items_length > 1 %} class="interior"{% endif %}>
        <div class="container">
            <div class="row">
                <div class="col-sm-4"></div>
                <div class="col-sm-8 copyright-txt">
                    <div class="version">GALAXY {{ version }}</div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

galaxy/templates/header.html
{% load url from future %}
{% load staticfiles %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-us"{% if ng_app %} ng-app="{{ ng_app }}"{% endif %}{% if ng_controller %} ng-controller="{{ ng_controller }}"{% endif %}>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Ansible, Inc" />
    <link rel="shortcut icon" href="/static/img/favicon.ico" />

    {% if ng_controller %}
    <title ng-bind="getTitle()"></title>
    {% else %}
    <title>Galaxy{% if page_title %} | {{ page_title }}{% endif %}</title>
    {% endif %}
    
    {% block extra_head %}{% endblock %}

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/font-awesome.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/loaders.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/galaxy.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/angular-toggle-switch-bootstrap-3.css' %}" />

    {% for extra in extra_css %}<link href="{% static extra %}" rel='stylesheet' type='text/css' />{% endfor %}   

    <!-- JS -->
    <script type="text/javascript" src="{% static 'vendorjs/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/jquery.dotdotdot.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/angular.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/angular-resource.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/angular-route.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/angular-sanitize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/angular-cookies.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/angular-animate.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/ui-bootstrap-tpls.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/underscore-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/angular-toggle-switch.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/angulartics.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendorjs/angulartics-ga.min.js' %}"></script>
    
    <script>
        var GLOBAL_DEBUG = "{{ debug }}";
        var GLOBAL_VERSION = "{{ version }}"
    </script>

    {% for extra in extra_js %}<script type="text/javascript" src="{% static extra %}"></script>
    {% endfor %}

</head>
<body>

galaxy/templates/home_title.html
<h1><span class="ansible-color">Galaxy</span> is your hub for finding, reusing and sharing Ansible content</h1>

galaxy/templates/list_top.html
{% extends 'base.html' %}
{% block general_content %}
 <div class="row-fluid">
  {% for tag, ranks in top_items %}
  <div class="span4 well well-small topbox">
   <h3><a href="{% url "main:list-category" tag %}">{{tag|capfirst}}</a></h3>
   <table class="table">
   {% for rank in ranks %}
    <tr>
     <td><a href="{% url "main:user-view" rank.role.owner.username %}">{{rank.role.owner.username}}</a>.<a href="{% url "main:role-view" rank.role.owner.username rank.role.name %}">{{rank.role.name}}</a><br /><strong>{{rank.average_score|floatformat:"2"}}</strong></td>
     <td>{{rank.role.rolerating_set.all|length}} reviews</td>
    </tr>
   {% endfor %}
    <tr>
     <td colspan="2"><a class="btn" href="{% url "main:list-category" tag %}">view more&nbsp;&nbsp;<i class="icon-chevron-sign-right"></i></a></td>
    </tr>
   </table>
  </div>
  {% if forloop.counter|divisibleby:"3" %}
 </div>
 <div class="row-fluid">
  {% endif %}
  {% endfor %}
 </div>
{% endblock %}

galaxy/templates/menu.html
<ul class="nav navbar-nav navbar-right" id="galaxy-nav-items" {% if use_menu_controller %} ng-controller="MenuCtrl" {% endif %}>
    <li {% if url_items.1.0 == 'explore' %} class="active" {% endif %}><a href="{% url 'main:explore' %}#/">Explore</a></li>
    <li id="nav-menu-browse-roles"><a href="{% url 'main:list-category' %}#/roles">Browse Roles</a></li>
    <li id="nav-menu-browse-authors"><a href="/authors/">Browse Authors</a></li>
    {% if not user.is_authenticated %}
        <li><a {% if not use_menu_controller %} href="/accounts/login/" {% endif %}
            {% if use_menu_controller %} href="" ng-click="redirectToSignin()" {% endif %}>Sign In</a></li>
    {% else %}
        <li {% if url_items.1.0 == 'roleadd' %} class="active" {% endif %}><a type="button" href="/roleadd#/">My Roles</a></li>
        {% if url_items.1.0 == 'accounts' and url_items.2.0 == 'profile' or url_items.2.0 == 'email' %}
            <li class="dropdown active">
        {% else %}
            <li id="nav-menu-dropdown" class="dropdown">
        {% endif %}
            <a href class="dropdown-toggle" data-toggle="dropdown" >
                <i class="fa fa-user"></i> <span class="username">{{ user.username }}</span> <span class="caret"></span></a>
            <ul class="dropdown-menu dropdown-menu-right user-menu">
                <li><a href="/imports#/">My Imports</a></li>
                <li><a href="{% url 'account_email' %}">Manage E-mail</a></li>
                {% url 'socialaccount_connections' as connections_url %}
                {% if connections_url %}
                    <li><a href="{{ connections_url }}">Manage Linked Accounts</a></li>
                {% endif %}
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'account_logout' %}"><i class="fa fa-sign-out"></i> Sign out</a></li>
            </ul>
        </li>
    {% endif %}
</ul>